---
- name: Install and setup needed software
 - include_tasks: prework.yml

- name: install wordpress
  include_tasks: install_wp.yml

- name: configure wordpress
  include_tasks: wp_config.yml

- name: create wordpress db
  include_tasks: create_wp_db.yml