---
- name: Copy wordpress template file
  shell: cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  become: true
  become_user: root

- name: replace lines in wp-config.php
  replace:
    path: /var/www/html/wp-config.php
    regexp: "{{ item.og_line }}"
    line: "{{ item.replacement }}"
  loop:
    - { og_line: "database_name_here", replacement: "{{ DBName }}"}
    - { og_line: "username_here", replacement: "{{ DBUser }}"}
    - { og_line: "password_here", replacement: "{{ DBPassword }}"}
  # no_log: true
  become: true
  become_user: root

- name: chown files
  file:
    path: /var/www/html
    owner: apache
    group: apache
    state: directory
    recurse: true
  become: true
  become_user: root