---
- name: Change password of ansible_usr
  hosts: "{{ survey_target }}"

  tasks:
  - name: change user password
    user:
      name: ansible_usr
      password: "{{ new_pass|password_hash('sha512') }}"
    become_user: root
    become: true