---
# needs improvement
deb_server1:
  hosts:
    44.211.191.35
deb_server2:
  hosts:
    54.161.213.125
rh_server1:
  hosts:
    54.87.181.219
rh_server2:
  hosts:
    44.202.5.32
all:
  vars:
    # testing="inventory vars win"
    ansible_ssh_pass: "{{ ansible_usr_pass }}"