---
# needs improvement
deb_server1:
  hosts:
    35.175.138.92
deb_server2:
  hosts:
    44.211.170.76
rh_server1:
  hosts:
    3.83.101.0
rh_server2:
  hosts:
    44.202.132.154
all:
  vars:
    # testing="inventory vars win"
    ansible_ssh_pass: "{{ ansible_usr_pass }}"
    ansible_become_pass: "{{ ansible_usr_pass }}"