---
# needs improvement
deb_server1:
  hosts:
    54.87.38.24
deb_server2:
  hosts:
    54.235.1.110
rh_server1:
  hosts:
    52.201.236.29
rh_server2:
  hosts:
    3.80.49.233
all:
  vars:
    # testing="inventory vars win"
    ansible_ssh_pass: "{{ ansible_usr_pass }}"
    ansible_become_pass: "{{ ansible_usr_pass }}"