---
- name: Generate ssh key and send public key to remote server, then scp file
  hosts: "{{ survey_target }}"
  vars:
    user_pass: "{{ ssh_user_pass }}"
    expect_ver: "{{ survey_expect_ver | default('perl')}}"
  roles:
    - role: gen_ssh_key_perl
      when: expect_ver == 'perl'
    - role: gen_ssh_key_ansible
      when: expect_ver == 'ansible'
    - role: test_scp