---
# ansible-playbook var_precedence.yml --extra-vars "survey_target=server2" -v
# ansible-playbook var_precedence.yml --extra-vars "survey_target=server2 testing='extra vars always win'" -v
- name: test variable precedence
  hosts: "{{ survey_target }}"
  vars:
    testing: "play vars win"
  roles:
    # - name: var_precedence
    #   vars:
    #     testing: "role params win"
    - name: var_precedence
    - name: var_precedence

# role defaults < inventory vars < play vars < role vars < role params < extra vars