---
# ansible-playbook var_precedence.yml --extra-vars "survey_target=server2" -v
# ansible-playbook var_precedence.yml --extra-vars "survey_target=server2 testing='extra vars always win'" -v
- name: test variable precedence
  # role defaults < inventory vars < play vars < role vars < role params < extra vars
  hosts: "{{ survey_target }}"
  vars:
    testing: "play vars win"
  roles:
    - vars_only # the testing2 variable from this role will be used in vars_precedence role
    - var_precedence
    # - name: var_precedence
    #   vars:
    #     testing: "role params win"

    # Calling a role more than once will result in only the first once being executed
    # - name: var_precedence
    # - name: var_precedence

    # Using different role params will cause the role to be executed twice
    # - name: var_precedence
    #   vars:
    #     testing: "role execution 1"
    # - name: var_precedence
    #   vars:
    #     testing: "role execution 2"

