---
- name: Download pexpect
  block:
  - name: Download pexpect (Debian)
    apt:
      name: python3-pexpect
      update_cache: yes
    when: ansible_distribution == "Debian"
  - name: Download pexpect (Debian)
    dnf:
      name: python3-pexpect
    when: ansible_distribution == "Redhat"
  become: true
  become_user: root


- name: Run the bash script and provide responses
  expect:
    command: "{{ home_dir }}/read-input.sh"
    responses:
      'pie\?': 'key lime'
      'Nonexistent question': "shouldn't need this answer"
      'Enter file.*:': 'ansible-test-pie.txt'
    echo: true
  register: output
  become: true
  become_user: root

- name: Show output from script
  debug:
    var: output.stdout