---
- name: Template in the bash script
  template:
    src: read-input.sh.j2
    dest: "{{ home_dir }}/read-input.sh"
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: '0777'
  become: true
  become_user: root

- name: Create testing directory
  file:
    path: "{{ home_dir }}/testing"
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: "0666"
    state: directory
  become: true
  become_user: root

- name: Run script with perl (if using)
  include_tasks: perl_ver.yml
  when: expect_ver == 'perl'

- name: Run script with ansible expect module (if using)
  expect:
    command: "{{ home_dir }}/read-input.sh"
    responses:
      - 'pie\?': 'key lime'
      - 'Nonexistent question': "shouldn't need this answer"
      - 'Enter file.*:': 'ansible-test-pie.txt'
    echo: true
  become: true
  become_user: root
  when: expect_ver == 'ansible'