---
- name: Download perl expect.pm (Debian)
  apt:
    name: libexpect-perl
    update_cache: yes
  become: true
  become_user: root
  when: ansible_distribution == "Debian"

- name: Download perl (Redhat)
  dnf:
    name: perl
  become: true
  become_user: root
  when: ansible_distribution == "RedHat"

- name: Template in simple_expect perl script
  template:
    src: simple-expect.pl.j2
    dest: "{{ home_dir }}/simple-expect.pl"
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: '0777'
  become: true
  become_user: root

- name: Run the simple expect script
  shell: "perl {{ home_dir }}/simple-expect.pl"
  register: output
  become: true
  become_user: root

- name: Show output from script
  debug:
    var: output.stdout