---
# Generates an ssh key and copies it to a server using the ansible expect module
- name: generate ssh key
  expect:
    command: "ssh-keygen"
    responses:
      'Enter file.*:': ''
      'Overwrite \(y\/n\)\?': 'yes'
      'Enter passphrase \(empty for no passphrase\):': ''
      'Enter same passphrase again:': ''
    echo: true
  register: gen_output
  become: true
  become_user: root

- name: print keygen output
  debug:
    var: gen_output

- name: ssh-copy key to remote server
  expect:
    command: "ssh-copy-id {{ scp_user }}@{{ scp_host }}"
    responses:
      'Are you sure.*connecting \(yes\/no\/\[fingerprint\]\)\?': 'yes'
      '.*password:': '{{ user_pass }}'
    echo: true
  register: copy_output
  become: true
  become_user: root

- name: print ssh-copy output
  debug:
    var: copy_output