---
# Create user with ssh access through password authentication
- name: Create user with sudoer privileges (Debian)
  user:
    name: "{{ username }}"
    create_home: yes
    password: "{{ survey_pass|password_hash('sha512') }}"
    groups: sudo
  when: ansible_distribution == "Debian"
  become: true
  become_user: root

- name: Create user with sudoer privileges (RedHat)
  user:
    name: "{{ username }}"
    create_home: yes
    password: "{{ survey_pass|password_hash('sha512') }}"
    groups: wheel
  when: ansible_distribution == "RedHat"
  become: true
  become_user: root

# - name: Edit /etc/ssh/ssh_config
#   include_tasks: edit_sshd_config.yml
#   become: true
#   become_user: root

- name: Edit /etc/ssh/ssh_config (v2)
  include_tasks: edit_sshd_config.yml
  vars:
    directive: '{{ edits.directive }}'
    delimiter: '{{ edits.delimiter }}'
  loop:
    - { directive: "AllowUsers", delimiter: " " }
    - { directive: "Match User", delimiter: "," }
  loop_control:
    loop_var: edits
  register: result

- name: print result
  debug:
    var: result

# Consider only restarting when sshd_config is changed
- name: Restart ssh (Debian)
  systemd:
    name: ssh
    state: restarted
  when: ansible_distribution == "Debian"
  become: true
  become_user: root

- name: Restart sshd (Redhat)
  systemd:
    name: sshd
    state: restarted
  when: ansible_distribution == "RedHat"
  become: true
  become_user: root